version: '3.8'

services:
  mongo:
    image: mongo:6.0.4
    restart: unless-stopped
    container_name: debbuggeando-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
      MONGO_INITDB_DATABASE: ecommercedb
    volumes:
      - ./init/ecommercedb.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    container_name: debbuggeando-expresMongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'secret'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'sa'
      ME_CONFIG_BASICAUTH_PASSWORD: 'sa'
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"

  springboot-app:
    build: .
    container_name: springboot-ecommerce
    ports:
      - "8084:8084"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
    depends_on:
      mongo:
        condition: service_healthy
      mongo-express:
        condition: service_started